### ISSUE TITLE
Wappalyzer technologies link has changed

### ISSUE THREAD

**Issue by afreudenreich** [RossGeerlings/webstor#2]
Hi,

Just to let you know: it seems that a few days ago Wappalyzer changed their technologies.json file to a different structure (i.e. to several separate json files in a folder). This basically breaks the ability to download their technology signatures.

It shouldn't be too hard to iterate through the folder and combine them into one json file (or load the content of each into the database while iterating). I'll give it a try and post any updates here if you don't beat me to it.
I think the github API might be a good way to start: https://api.github.com/repos/AliasIO/wappalyzer/contents/src/technologies?ref=master

Thanks,
Andreas

**Comment by RossGeerlings** [comment]
Thank you for noticing this.  I will try to have this tested and resolved in the next day or so.

**Comment by RossGeerlings** [comment]
The Wappalyzer issue should be resolved.  Thank you for you help on this, Andreas.
